export const sample_foods=[
    {
        id:'1',
        name: 'Pizza Pepperoni',
        cookTime:'10-20',
        price:10,
        favorite:false,
        origins:['italy'],
        stars:4.5,
        imageurl:'food-1',
        tags:['FastFood','Pizza','Lunch'],
    },
    {
        id:'2',
        name: 'Meatball',
        cookTime:'20-30',
        price:20,
        favorite:true,
        origins:['persia','middle east','china'],
        stars:5,
        imageurl:'food-2',
        tags:['SlowFood','Lunch'],
    },
    {
        id:'3',
        name: 'Hamburger',
        cookTime:'10-15',
        price:5,
        favorite:false,
        origins:['germany','us'],
        stars:3.5,
        imageurl:'food-3',
        tags:['FastFood','Hamburger'],
    },
    {
        id:'4',
        name: 'Fried potatoes',
        cookTime:'15-20',
        price:2,
        favorite:true,
        origins:['belgium','france'],
        stars:3,
        imageurl:'food-4',
        tags:['FastFood','Fry'],
    },
    {
        id:'5',
        name: 'Chicken Soup',
        cookTime:'40-50',
        price:11,
        favorite:false,
        origins:['india','asia'],
        stars:3.5,
        imageurl:'food-5',
        tags:['SlowFood','Soup'],
    },
    {
        id:'6',
        name: 'Vegetables Pizza',
        cookTime:'40-50',
        price:9,
        favorite:false,
        origins:['italy'],
        stars:4.0,
        imageurl:'food-6',
        tags:['FastFood','Pizza','Lunch'],
    },

];

export const sample_tags=[
    {name:'All', count: 6},
    {name:'FastFood',count:4},
    {name:'Veggies',count:2},
    {name:'Soup',count:3},
    {name:'Cocktails',count:2},
    {name:'Lunck-Special',count:1},
    {name:'Paneer-Special',count:1},
    {name:'Starters',count:1},
];
